### ISSUE TITLE
Shell portability suggestion.

### ISSUE THREAD

**Issue by masonke** [aguther/nmonchart#2]
Suggestion, in nmonchart, change the shebang line from 
#!/usr/bin/ksh
to
##!/usr/bin/env ksh 

This lets the script run on systems like Macs that have the shell in a different location. 

I would have made the change myself, but I cannot seem to crate a branch in the repo

**Comment by aguther** [comment]
Thank you for the suggestion!

I thought about it and I think it would be better to bring this to the original author (http://nmon.sourceforge.net/pmwiki.php?n=Site.Nmonchart).

The reason is that I just wanted to provide a SPEC file for nmonchart and no different version of it. Maybe I should do the same with my spec file :-)

**Comment by masonke** [comment]
I will send it to him on sourceforge. Git is just so much easier to use, it is a shame the repo isnt here.

Thanks
